config/routes.rb
Rails.application.routes.draw do
  devise_for :users, except: [:destroy]
  resources :departures, except: [:destroy, :update]
  resources :entries, except: [:destroy, :update]
  resources :stuffs
  resources :users
  root to: 'home#index'
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end
  get 'stuff_log' => 'stuffs#log'

end

app/models/stuff.rb
class Stuff < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates_numericality_of :amount, greater_than_or_equal_to: 0
  has_many :entries
  has_many :departures

  before_destroy :check_entry_and_departure

  scope :ordered, -> { order :name }

  def check_entry_and_departure
    return true if (entries.count == 0 and departures.count == 0)
    errors.add(:base, "Não é possível remover materiais com entradas/saídas cadastradas.")
    false
  end

  def can_be_removed?
    return true if (departures.count == 0 and entries.count == 0)
    return false
  end
end

app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stuff, only: [:show, :edit, :update, :destroy]

  # GET /stuffs
  # GET /stuffs.json
  def index
    @stuffs = Stuff.all
  end

  # GET /stuffs/1
  # GET /stuffs/1.json
  def show
  end

  # GET /stuffs/new
  def new
    @stuff = Stuff.new
  end

  # GET /stuffs/1/edit
  def edit
  end

  # POST /stuffs
  # POST /stuffs.json
  def create
    @stuff = Stuff.new(stuff_params)

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to stuffs_path, notice: 'Material criado com sucesso!' }
        format.json { render :show, status: :created, location: @stuff }
      else
        format.html { render :new }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuffs/1
  # PATCH/PUT /stuffs/1.json
  def update
    respond_to do |format|
      if @stuff.update(stuff_params)
        format.html { redirect_to @stuff, notice: 'Material atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @stuff }
      else
        format.html { render :edit }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1
  # DELETE /stuffs/1.json
  def destroy
    if @stuff.destroy
      respond_to do |format|
        format.html { redirect_to stuffs_url, notice: 'Material removido com sucesso' }
        format.json { head :no_content }
      end
    else
      redirect_to stuffs_path, flash: { error: @stuff.errors.full_messages }
    end
  end


  def log
    @stuff = Stuff.find(params[:stuff_id])
    respond_to do |format|
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stuff
    @stuff = Stuff.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stuff_params
    params.require(:stuff).permit(:name)
  end
end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/views/stuffs/_form.html.erb
<%= form_for @stuff, :html => { :class => "form-horizontal stuff" } do |f| %>

  <% if @stuff.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@stuff.errors.count, "error") %> prohibited this stuff from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @stuff.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stuffs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/stuffs/_log_table.html.erb
<%- model_class = Entry -%>
<div class="alert alert-info" align="center"><strong>Entradas</strong></div>
<table  class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:responsible) %></th>
      <th><%= model_class.human_attribute_name(:stuff) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
    </tr>
  </thead>
  <tbody>
  <% @stuff.entries.ordered.each do |e| %>
      <tr>
        <td><%= e.audits.first.user.login %></td>
        <td><%= e.stuff.name%></td>
        <td><%= e.amount%></td>
      </tr>

  <% end %>
  </tbody>
</table>

<%- model_class = Departure -%>
<div class="alert alert-warning" align="center"><strong>Retiradas</strong></div>
<table  class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:responsible) %></th>
      <th><%= model_class.human_attribute_name(:stuff) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
    </tr>
  </thead>
  <tbody>
  <% @stuff.departures.ordered.each do |e| %>
      <tr>
        <td><%= e.audits.first.user.login %></td>
        <td><%= e.stuff.name%></td>
        <td><%= e.amount%></td>
      </tr>

  <% end %>
  </tbody>
</table>

app/views/stuffs/_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Quantidade</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <div class="alert alert-warning"> Horário permitido para retirada: 09h às 18h</div>
    <div id="#stuffs-table">
      <% @stuffs.each do |stuff| %>
        <tr>
          <td><%= stuff.name %></td>
          <td><%= stuff.amount %></td>
          <td>
            <%= link_to '<i class="fa fa-arrow-circle-up" aria-hidden="true"></i> Entrada'.html_safe, new_entry_path(stuff_id: stuff.id),
                        {:remote => true,
                          'data-toggle' => "modal", 'data-target' => '#new_entry_modal', class: 'btn btn-info btn-md'}  %>
            <%= link_to '<i class="fa fa-arrow-circle-down" aria-hidden="true"></i> Retirada'.html_safe, new_departure_path(stuff_id: stuff.id),
                        {:remote => true,
                          'data-toggle' => "modal", 'data-target' => '#new_departure_modal', class: 'btn btn-warning btn-md'} %>
            <%= link_to "<i class='fa fa-pencil-square-o' aria-hidden='true'></i> ".html_safe.concat(t('.edit', :default => t("helpers.links.edit"))),
                        edit_stuff_path(stuff), :class => 'btn btn-default btn-md' %>
            <%= link_to '<i class="fa fa-bar-chart" aria-hidden="true"></i> Log de Entradas/Retiradas'.html_safe, stuff_log_path(stuff_id: stuff.id),
                        {:remote => true,
                          'data-toggle' => "modal", 'data-target' => '#stuff_log_modal', class: 'btn btn-default btn-md'} %>
            <%= link_to "<i class='fa fa-trash' aria-hidden='true'></i> ".html_safe.concat(t('.destroy', :default => t("helpers.links.destroy"))),
                        stuff_path(stuff),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-md btn-danger' if stuff.can_be_removed? %>
          </td>
        </tr>
      <% end %>
    </div>
  </tbody>
</table>

app/views/stuffs/edit.html.erb
<%- model_class = Stuff -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stuffs/index.html.erb
<%- model_class = Stuff -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div id="stuffs-table">
  <%= render 'table', stuffs: @stuffs %>
</div>
<%= modal_dialog id: "modal",
         header: { show_close: true, dismiss: 'modal', title: 'Entrada' },
         body:   { content: 'form' },
         footer: { content: content_tag(:button, 'Save', class: 'btn') } %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_stuff_path,
            :class => 'btn btn-primary' %>

<div class="modal fade" id="new_entry_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="nome_entrada" align="center">Entrada</h4>
      </div>
      <div id="entry_form" class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="new_departure_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="nome_entrada" align="center">Retirada</h4>
      </div>
      <div id="departure_form" class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="stuff_log_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="nome_entrada" align="center">Log de Entradas/Retiradas</h4>
      </div>
      <div id="stuff_log_table" class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/stuffs/log.js.erb
$("#stuff_log_table").html("<%= escape_javascript(render 'log_table', modal: true) %>");

app/views/stuffs/new.html.erb
<%- model_class = Stuff -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stuffs/show.html.erb
<%- model_class = Stuff -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @stuff.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              stuffs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_stuff_path(@stuff), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              stuff_path(@stuff),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>