config/routes.rb
Rails.application.routes.draw do
  devise_for :users, except: [:destroy]
  resources :departures, except: [:destroy, :update]
  resources :entries, except: [:destroy, :update]
  resources :stuffs
  resources :users
  root to: 'home#index'
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end
  get 'stuff_log' => 'stuffs#log'

end

app/models/departure.rb
class Departure < ActiveRecord::Base
  audited

  belongs_to :stuff

  validates :stuff_id, :amount, presence: true
  validate :amount_enough_to_departure?
  validates :created_at, horary_day: true # => custom validator at validator/horary_day_validator.rb

  after_save :update_stuff_amount

  scope :ordered, -> { order created_at: :desc }

  def update_stuff_amount
    stuff.update(amount: (stuff.amount - amount))
  end

  def amount_enough_to_departure?
    return unless stuff
    if (stuff.amount - self.amount) < 0
      errors.add(:amount, "para retirada permitida: #{stuff.amount}")
    end
  end
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_departure, only: [:show, :edit, :update, :destroy]

  # GET /departures
  # GET /departures.json
  def index
    @departures = Departure.ordered
  end

  # GET /departures/new
  def new
    @departure = Departure.new
    @stuff = Stuff.find(params[:stuff_id])
    respond_to do |format|
      format.js
    end
  end

  # POST /departures
  # POST /departures.json
  def create
    @departure = Departure.new(departure_params)
    respond_to do |format|
      if @departure.save
        @stuffs = Stuff.ordered
        format.html { redirect_to departures_url, notice: 'Entrada criada com sucesso!' }
        format.json { render :show, status: :created, location: @entry }
        format.js
      else
        @stuff = Stuff.find(params["departure"]["stuff_id"])
        format.js { render :new }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def departure_params
    params.require(:departure).permit(:amount, :stuff_id)
  end
end

app/helpers/departures_helper.rb
module DeparturesHelper
end

app/views/departures/_form.html.erb
<%= form_for(@departure, remote: true, html: {role: :form, 'data-model' => 'departure'}) do |f| %>
  <div class="alert alert-warning"> Horário permitido para retirada: 09h às 18h</div>
  <% if @departure.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @departure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="form-group">
    <h4>Item: <%= @stuff.name %></h4>
    <%= f.hidden_field :stuff_id, :value => @stuff.id %>
    <%= f.label :amount, class:   'control-label' %><br>
    <%= f.number_field :amount, class: 'form-control' %>
    <span class="help-block"></span>
  </div>

  <div class="actions">
    <%= f.submit 'Finalizar', class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/departures/create.js.erb
<% unless @departure.errors.any? %>
	$('#stuffs-table').html("<%= raw escape_javascript(render(partial: 'stuffs/table', departure: @departure)) %>");
	$('#new_departure_modal').modal('hide');
<% end %>

app/views/departures/edit.html.erb
<h1>Editing Departure</h1>

<%= render 'form' %>

<%= link_to 'Show', @departure %> |
<%= link_to 'Back', departures_path %>

app/views/departures/index.html.erb
<%- model_class = Departure -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:responsible) %></th>
      <th><%= model_class.human_attribute_name(:stuff) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
    </tr>
  </thead>
  <tbody>
    <% @departures.each do |departure| %>
      <tr>
        <td><%= departure.audits.first.user.login %></td>
        <td><%= departure.stuff.name %></td>
        <td><%= departure.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departures/new.html.erb
<h1>New Departure</h1>

<%= render 'form' %>

<%= link_to 'Back', departures_path %>

app/views/departures/new.js.erb
$("#departure_form").html("<%= escape_javascript(render 'form', modal: true) %>");

app/views/departures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @departure.amount %>
</p>

<p>
  <strong>Stuff:</strong>
  <%= @departure.stuff %>
</p>

<%= link_to 'Edit', edit_departure_path(@departure) %> |
<%= link_to 'Back', departures_path %>