config/routes.rb
Rails.application.routes.draw do
  devise_for :users, except: [:destroy]
  resources :departures, except: [:destroy, :update]
  resources :entries, except: [:destroy, :update]
  resources :stuffs
  resources :users
  root to: 'home#index'
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end
  get 'stuff_log' => 'stuffs#log'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AppAlmoxarifado" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= root_path %>>AppAlmoxarifado</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Deslogar", sign_out_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Recursos</h3>
            <ul class="nav nav-list">
            <p><%= link_to "<i class='fa fa-users fa-2' aria-hidden='true'></i> ".html_safe.concat(User.model_name.human.pluralize.titleize),
                        users_path, :class => 'btn btn-default btn-md' %></p>
            <p><%= link_to "<i class='fa fa-folder fa-2' aria-hidden='true'></i> ".html_safe.concat(Stuff.model_name.human.pluralize.titleize),
                        stuffs_path, :class => 'btn btn-default btn-md' %></p>
            <p><%= link_to "<i class='fa fa-arrow-up fa-2' aria-hidden='true'></i> ".html_safe.concat(Entry.model_name.human.pluralize.titleize),
                        entries_path, :class => 'btn btn-default btn-md' %></p>
            <p><%= link_to "<i class='fa fa-arrow-down fa-2' aria-hidden='true'></i> ".html_safe.concat(Departure.model_name.human.pluralize.titleize),
                        departures_path, :class => 'btn btn-default btn-md' %></p>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

    </div> <!-- /container -->
    <footer class="footer" align="center">
      <p align="center"><%= Date.today.year %> &copy; Desenvolvido por Gustavo Rocha </p>
      <p align="center">gustavoufms@gmail.com</p>
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppAlmoxarifado</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="login-body">
<%= yield %>

</body>
</html>